import { sampleContent } from "./globals";
import { UserInput } from "./interfaces";

export const sampleUsers : UserInput[] = [
    {
        id: "feed1",
        ageInterest: [18,30],
        alcohol: "Often",
        attributes: ["Soccer", "Music"],
        birthday: new Date(2000,1,1),
        email: `1@${sampleContent.uni}.edu`,
        gender: "Male",
        genderInterest: ["Male","Female"],
        images: [],
        smoking: "Sometimes",
        name: "User 1",
        description: "This is a little description about me",
    },
    {
        id: "feed2",
        ageInterest: [18,30],
        alcohol: "Never",
        attributes: ["Basketball", "Cooking", "Running"],
        birthday: new Date(2002,1,1),
        email: `2@${sampleContent.uni}.edu`,
        gender: "Male",
        genderInterest: ["Male","Female"],
        images: [],
        smoking: "Never",
        name: "User 2",
        description: "Should be in feed",
    },
    {
        id: "feed3",
        ageInterest: [18,30],
        alcohol: "Sometimes",
        attributes: ["Volleyball", "Rap"],
        birthday: new Date(2004,1,1),
        email: `3@${sampleContent.uni}.edu`,
        gender: "Female",
        genderInterest: ["Male","Female"],
        images: [],
        smoking: "Sometimes",
        name: "User 3",
        description: "Should be in feed",
    },
    {
        id: "feed4",
        ageInterest: [18,30],
        alcohol: "Never",
        attributes: ["Swim", "Baking"],
        birthday: new Date(2006,1,1),
        email: `4@${sampleContent.uni}.edu`,
        gender: "Female",
        genderInterest: ["Male","Female"],
        images: [],
        smoking: "Never",
        name: "User 5",
        description: "Should be in feed",
    },
    {
        id: "newmatch1",
        ageInterest: [18,30],
        alcohol: "Often",
        attributes: ["Concerts", "Gaming"],
        birthday: new Date(2000,1,1),
        email: `5@${sampleContent.uni}.edu`,
        gender: "Male",
        genderInterest: ["Female"],
        images: [],
        smoking: "Never",
        name: "New Match 1",
        description: "Should be in feed",
    },
    {
        id: "newmatch2",
        ageInterest: [18,30],
        alcohol: "Often",
        attributes: ["Soccer", "Music"],
        birthday: new Date(2000,1,1),
        email: `6@${sampleContent.uni}.edu`,
        gender: "Female",
        genderInterest: ["Female"],
        images: [],
        smoking: "Never",
        name: "New Match 2",
        description: "Should be in feed",
    },
    {
        id: "oldmatch1",
        ageInterest: [18,30],
        alcohol: "Often",
        attributes: ["Soccer", "Music"],
        birthday: new Date(2000,1,1),
        email: `7@${sampleContent.uni}.edu`,
        gender: "Male",
        genderInterest: ["Female"],
        images: [],
        smoking: "Never",
        name: "Old Match 1",
        description: "Should be in feed",
    },
    {
        id: "oldmatch2",
        ageInterest: [18,30],
        alcohol: "Often",
        attributes: ["Soccer", "Music"],
        birthday: new Date(2000,1,1),
        email: `8@${sampleContent.uni}.edu`,
        gender: "Female",
        genderInterest: ["Female"],
        images: [],
        smoking: "Never",
        name: "Old Match 1",
        description: "Should be in feed",
    },
]