import { sampleContent } from "./globals";
import { UserInput } from "./interfaces";

export const sampleUsers : UserInput[] = [
    {
        id: "feed1",
        ageInterest: [18,30],
        alcohol: "Often",
        attributes: ["Soccer", "Music"],
        birthday: new Date(2000,1,1),
        email: `1@${sampleContent.uni}.edu`,
        gender: "Male",
        genderInterest: ["Male","Female"],
        images: [
        ],
        smoking: "Sometimes",
        name: "Keanu",
        description: "Actor aka John Wick aka Neo",
    },
    {
        id: "feed2",
        ageInterest: [18,30],
        alcohol: "Never",
        attributes: ["Basketball", "Cooking", "Running"],
        birthday: new Date(2002,1,1),
        email: `2@${sampleContent.uni}.edu`,
        gender: "Male",
        genderInterest: ["Male","Female"],
        images: [
        ],
        smoking: "Never",
        name: "Leo",
        description: "Leonardo Wilhelm DiCaprio is an American actor and film producer. Known for his work in biographical and period films, he is the recipient of numerous accolades, including an Academy Award, a British Academy Film Award, and three Golden Globe Awards.",
    },
    {
        id: "feed3",
        ageInterest: [18,30],
        alcohol: "Sometimes",
        attributes: ["Volleyball", "Rap"],
        birthday: new Date(2004,1,1),
        email: `3@${sampleContent.uni}.edu`,
        gender: "Female",
        genderInterest: ["Male","Female"],
        images: [
        ],
        smoking: "Sometimes",
        name: "Scarlett",
        description: "Scarlett Ingrid Johansson is an American actress. The world's highest-paid actress in 2018 and 2019, she has been featured multiple times on the Forbes Celebrity 100 list. Time named her one of the 100 most influential people in the world in 2021.",
    },
    {
        id: "feed4",
        ageInterest: [18,30],
        alcohol: "Never",
        attributes: ["Swim", "Baking"],
        birthday: new Date(2006,1,1),
        email: `4@${sampleContent.uni}.edu`,
        gender: "Female",
        genderInterest: ["Male","Female"],
        images: [
        ],
        smoking: "Never",
        name: "Cate",
        description: "Catherine Elise Blanchett AC is an Australian actor and producer. She is recognised for her versatile work across independent films, blockbusters and the stage",
    },
    {
        id: "newmatch1",
        ageInterest: [18,30],
        alcohol: "Often",
        attributes: ["Concerts", "Gaming"],
        birthday: new Date(2000,1,1),
        email: `5@${sampleContent.uni}.edu`,
        gender: "Male",
        genderInterest: ["Female"],
        images: [
        ],
        smoking: "Never",
        name: "Morgan",
        description: " ",
    },
    {
        id: "newmatch2",
        ageInterest: [18,30],
        alcohol: "Often",
        attributes: ["Soccer", "Music"],
        birthday: new Date(2000,1,1),
        email: `6@${sampleContent.uni}.edu`,
        gender: "Female",
        genderInterest: ["Female"],
        images: [
        ],
        smoking: "Never",
        name: "Anne",
        description: "Anne Jacqueline Hathaway is an American actress. Her accolades include an Academy Award, a British Academy Film Award, a Golden Globe Award, and a Primetime Emmy Award. Her films have grossed over $6.8 billion worldwide, and she appeared on the Forbes Celebrity 100 list in 2009.",
    },
    {
        id: "oldmatch1",
        ageInterest: [18,30],
        alcohol: "Often",
        attributes: ["Soccer", "Music"],
        birthday: new Date(2000,1,1),
        email: `7@${sampleContent.uni}.edu`,
        gender: "Male",
        genderInterest: ["Female"],
        images: [
        ],
        smoking: "Never",
        name: "Samuel",
        description: "Motherfu...",
    },
    {
        id: "oldmatch2",
        ageInterest: [18,30],
        alcohol: "Often",
        attributes: ["Soccer", "Music"],
        birthday: new Date(2000,1,1),
        email: `8@${sampleContent.uni}.edu`,
        gender: "Female",
        genderInterest: ["Female"],
        images: [
        ],
        smoking: "Never",
        name: "Jennifer",
        description: "Hunger Games winner",
    },
]