export const URLs = {
    createUser: "/createUser",
    sendMessage: "/sendMessage",
    getChat: "/getChat",
    reportUser: "/reportUser",
    getNewMatches: "/getNewMatches",
    getNewChatPreviews: "/getChatPreviews",
    makeSwipe: "/makeSwipe",
    getFeed: "/getFeed",
    newVerification: "/newVerification",
    verifyUser: "/verifyUser",
    newCode: "/newCode",
    uploadImage: "/uploadImage",
    deleteImage: "/deleteImage",
    newOrder: "/newOrder",
    editUser: "/editUser",
    getCheckoutPage: "/getCheckoutPage",
    cancelSubscription: "/cancelSubscription",
    manageSubscription: "/manageSubscription",
    deleteAccount: "/deleteAccount",
    unlikeUser: "/unlikeUser",
    getProfile: "/getProfile",
    getStats: "/getStats",
    getSubscription: "/getSubscription",
    getSettings: "/getSettings",
    getPreferences: "/getPreferences",
    login: "/login",
    autoLogin: "/autoLogin",
    updatePushToken: "/updatePushToken",
    getAttributes: "/getAttributes",
    getClientIDs: "/getClientIDs",
    getMyProfile: "/getMyProfile",
    sendReadStatus: "/sendReadStatus",
    getReadStatus: "/getReadStatus",
    getPremiumPage: "/getPremiumPage",
    getAnnouncements: "/getAnnouncements",
    viewAnnouncement: "/viewAnnouncement",
    websocket: "/ws",

    // STRIPE
    webhook: "/webhook",

    // ADMIN
    deleteEverything: "/deleteEverything",
    createSample: "/createSample",
    clearInteractions: "/clearInteractions",
    purchasePremium: "/purchasePremium",
    makeAnnouncement: "/makeAnnouncement",
    ip: "192.168.86.47",
    port: 3000,

    // OAUTH
    googleOAuth: "https://www.googleapis.com/userinfo/v2/me",
}