export const globals = {
    genders: ["Male", "Female"],
    minAge: 18,
    maxAge: 30,
    maxUploads: 6,
    maxAttributes: 5,
    timeBeforeChatTimestamp: 1000 * 60 * 60,
    settingImages: "images",
    settingDescription: "description",
    settingGenderPreference: "gender preference",
    settingAgePreference: "age preference",
    maxPreviewMessageLength: 20,
    maxNameLength: 16,
    acceptableFileTypes: ["image/jpeg", "image/png"],
    pictureHeight: 136,
    pictureWidth: 102,
    maxPictureSize: 1024*1024*1,
    scrollAtPercentage: 0.95,
    apiRequestTimeout: 2,
    resendVerificationTimeout: 10,
    fadeDuration: 500,
    frequencies: ["Never", "Sometimes", "Often"],

    attributes: {
        "Sports": [
            {id: "id", value: "soccer"},
            {id: "id2", value: "basketball"},
            {id: String(Math.random()), value: String(Math.random())},
            {id: String(Math.random()), value: String(Math.random())},
            {id: String(Math.random()), value: String(Math.random())},
            {id: String(Math.random()), value: String(Math.random())},
            {id: String(Math.random()), value: String(Math.random())},
            {id: String(Math.random()), value: String(Math.random())},
            {id: String(Math.random()), value: String(Math.random())},
            {id: String(Math.random()), value: String(Math.random())},
            {id: String(Math.random()), value: String(Math.random())},
            {id: String(Math.random()), value: String(Math.random())},
            {id: String(Math.random()), value: String(Math.random())},
            {id: String(Math.random()), value: String(Math.random())},
            {id: String(Math.random()), value: String(Math.random())},
            {id: String(Math.random()), value: String(Math.random())},
            {id: String(Math.random()), value: String(Math.random())},
            {id: String(Math.random()), value: String(Math.random())},
            {id: String(Math.random()), value: String(Math.random())},
            {id: String(Math.random()), value: String(Math.random())},
            {id: String(Math.random()), value: String(Math.random())},
            {id: String(Math.random()), value: String(Math.random())},
            {id: String(Math.random()), value: String(Math.random())},

        ],
        "Music": [
            {id: "id3", value: "pop"},
            {id: "id4", value: "rap"},
        ]
    },

    green: "#4A991A",
    red: "#B81515",
    dark: "#222222",
    light: "#F3F0E7"
}