export const URLs = {
    server: "https://randomURL",
    createUser: "/createUser",
    sendMessage: "/sendMessage",
    getChat: "/getChat",
    reportUser: "/reportUser",
    getNewMatches: "/getNewMatches",
    getNewChatPreviews: "/getChatPreviews",
    makeSwipe: "/makeSwipe",
    getFeed: "/getFeed",
    newVerification: "/newVerification",
    verifyUser: "/verifyUser",
    newCode: "/newCode",
    uploadImage: "/uploadImage",
    deleteImage: "/deleteImage",
    newOrder: "/newOrder",
    editUser: "/editUser",
    getCheckoutPage: "/getCheckoutPage",
    cancelSubscription: "/cancelSubscription",
    manageSubscription: "/manageSubscription",
    deleteAccount: "/deleteAccount",
    unlikeUser: "/unlikeUser",
    getProfile: "/getProfile",
    getStats: "/getStats",
    getSubscription: "/getSubscription",
}